# Generated by Django 6.0.2 on 2026-03-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
