# Generated by Django 6.0.2 on 2026-03-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_visithistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
    ]
